<a href="https://colab.research.google.com/github/eerenkurt/ml-studies/blob/main/08-logistic-regression-classification/credit_card_default_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv("card.csv")

In [ ]:
df.head(3)

   ID  LIMIT_BAL  SEX  ...  PAY_AMT5  PAY_AMT6  default.payment.next.month
0   1    20000.0    2  ...       0.0       0.0                           1
1   2   120000.0    2  ...       0.0    2000.0                           1
2   3    90000.0    2  ...    1000.0    5000.0                           0

[3 rows x 25 columns]

In [ ]:
df=df.drop("ID",axis=1)

In [ ]:
y=df["default.payment.next.month"]
x=df.drop("default.payment.next.month",axis=1)

In [ ]:
df.shape

(30000, 24)

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.77,random_state=6)

In [ ]:
log = LogisticRegression()
model = log.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [ ]:
model.score(x_test,y_test)

0.7739130434782608

In [ ]:
x

       LIMIT_BAL  SEX  EDUCATION  ...  PAY_AMT4  PAY_AMT5  PAY_AMT6
0        20000.0    2          2  ...       0.0       0.0       0.0
1       120000.0    2          2  ...    1000.0       0.0    2000.0
2        90000.0    2          2  ...    1000.0    1000.0    5000.0
3        50000.0    2          2  ...    1100.0    1069.0    1000.0
4        50000.0    1          2  ...    9000.0     689.0     679.0
...          ...  ...        ...  ...       ...       ...       ...
29995   220000.0    1          3  ...    3047.0    5000.0    1000.0
29996   150000.0    1          3  ...     129.0       0.0       0.0
29997    30000.0    1          2  ...    4200.0    2000.0    3100.0
29998    80000.0    1          3  ...    1926.0   52964.0    1804.0
29999    50000.0    1          2  ...    1000.0    1000.0    1000.0

[30000 rows x 23 columns]

In [ ]:
denemex = np.array(x.iloc[1903])

In [ ]:
model.predict([denemex])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0])

In [ ]:
y.iloc[1903]

np.int64(0)