<a href="https://colab.research.google.com/github/eerenkurt/ml-studies/blob/main/15-customer-churn-prediction/bank_churn_analysis_ohe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

In [ ]:
df = pd.read_csv('Churn_Modelling.csv')

In [ ]:
df.head(4)

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0

[4 rows x 14 columns]

In [ ]:
df = df.drop(columns=['RowNumber','CustomerId','Surname'])

In [ ]:
df.head(3)

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1

[3 rows x 11 columns]

In [ ]:
df = pd.get_dummies(df,columns=['Geography','Gender'],drop_first=True)

In [ ]:
df.head(3)

   CreditScore  Age  Tenure  ...  Geography_Germany  Geography_Spain  Gender_Male
0          619   42       2  ...              False            False        False
1          608   41       1  ...              False             True        False
2          502   42       8  ...              False            False        False

[3 rows x 12 columns]

In [ ]:
y = df['Exited']
x = df.drop('Exited',axis=1)

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.7,random_state=61)

In [ ]:
rf = RandomForestClassifier()
model = rf.fit(x_train,y_train)
model.score(x_test,y_test)

0.861

In [ ]:
x.head(2)

   CreditScore  Age  Tenure  ...  Geography_Germany  Geography_Spain  Gender_Male
0          619   42       2  ...              False            False        False
1          608   41       1  ...              False             True        False

[2 rows x 11 columns]

In [ ]:
model.predict([[712,22,4,0,4,1,1,200000,False,False,True]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array([1])

In [ ]:
df = pd.read_csv('Churn_Modelling.csv')
df = df.drop(columns=['RowNumber','CustomerId','Surname'])

In [ ]:
df.head(3)

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1

[3 rows x 11 columns]

In [ ]:
ohe = OneHotEncoder()

In [ ]:
xd = ohe.fit_transform(df[['Geography','Gender']]).toarray()

In [ ]:
ohe.get_feature_names_out()

array(['Geography_France', 'Geography_Germany', 'Geography_Spain',
       'Gender_Female', 'Gender_Male'], dtype=object)

In [ ]:
xd = pd.DataFrame(xd)

In [ ]:
xd.columns = ohe.get_feature_names_out()

In [ ]:
xd

      Geography_France  Geography_Germany  ...  Gender_Female  Gender_Male
0                  1.0                0.0  ...            1.0          0.0
1                  0.0                0.0  ...            1.0          0.0
2                  1.0                0.0  ...            1.0          0.0
3                  1.0                0.0  ...            1.0          0.0
4                  0.0                0.0  ...            1.0          0.0
...                ...                ...  ...            ...          ...
9995               1.0                0.0  ...            0.0          1.0
9996               1.0                0.0  ...            0.0          1.0
9997               1.0                0.0  ...            1.0          0.0
9998               0.0                1.0  ...            0.0          1.0
9999               1.0                0.0  ...            1.0          0.0

[10000 rows x 5 columns]

In [ ]:
df.head(3)

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1

[3 rows x 11 columns]

In [ ]:
df = df.drop(columns=['Geography','Gender'])

In [ ]:
df.head(3)

   CreditScore  Age  Tenure  ...  IsActiveMember  EstimatedSalary  Exited
0          619   42       2  ...               1        101348.88       1
1          608   41       1  ...               1        112542.58       0
2          502   42       8  ...               0        113931.57       1

[3 rows x 9 columns]

In [ ]:
df[xd.columns] = xd

In [ ]:
df.head(3)

   CreditScore  Age  Tenure  ...  Geography_Spain  Gender_Female  Gender_Male
0          619   42       2  ...              0.0            1.0          0.0
1          608   41       1  ...              1.0            1.0          0.0
2          502   42       8  ...              0.0            1.0          0.0

[3 rows x 14 columns]

In [ ]:
y = df['Exited']
x = df.drop('Exited',axis=1)

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
tree = DecisionTreeClassifier()
model = tree.fit(x,y)
model.score(x,y)

# Overfitting oldu :(

1.0

In [ ]:
ohe.transform([["France","Female"]]).toarray()

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0., 1., 0.]])