<a href="https://colab.research.google.com/github/eerenkurt/ml-studies/blob/main/11-random-forest-regression/insurance_cost_random_forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv('insurance.csv')

In [ ]:
df.head(3)

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523
2   28    male  33.00         3     no  southeast   4449.4620

In [ ]:
df = pd.get_dummies(df,columns=["sex","smoker","region"],drop_first=True)

In [ ]:
df.head(3)

   age    bmi  children  ...  region_northwest  region_southeast  region_southwest
0   19  27.90         0  ...             False             False              True
1   18  33.77         1  ...             False              True             False
2   28  33.00         3  ...             False              True             False

[3 rows x 9 columns]

In [ ]:
y = df["charges"]
x = df.drop(columns=["charges"]) #("charges",axis = 1)

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.7,random_state=22)

In [ ]:
lr = LinearRegression()
model = lr.fit(x_train,y_train)
model.score(x_test,y_test)

0.7470296560638764

In [ ]:
rf = RandomForestRegressor(n_estimators=200)
model = rf.fit(x_train,y_train)
model.score(x_test,y_test)

0.845495243310059

In [ ]:
x.head(3)

   age    bmi  children  ...  region_northwest  region_southeast  region_southwest
0   19  27.90         0  ...             False             False              True
1   18  33.77         1  ...             False              True             False
2   28  33.00         3  ...             False              True             False

[3 rows x 8 columns]

In [ ]:
model.predict([[31,27.4,0,1,1,1,0,0]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([18070.02780175])