<a href="https://colab.research.google.com/github/eerenkurt/ml-studies/blob/main/04-train-test-split/audi_price_prediction_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv('audi.csv')

In [ ]:
df.head(3)

   index    Year       Type  ...  PriceRank PPYRank  Score
0      0  2018.0  Hatchback  ...        163     340    718
1      4  2016.0  Hatchback  ...        330     276    828
2      7  2015.0  Hatchback  ...        327      94    642

[3 rows x 16 columns]

In [ ]:
df = df[["Year", "Type", "Mileage(miles)", "Engine", "PS", "Transmission", "Fuel", "Number_of_Owners","Price(£)"]]

In [ ]:
df.head(3)

     Year       Type  Mileage(miles)  ...    Fuel  Number_of_Owners Price(£)
0  2018.0  Hatchback         44000.0  ...  Diesel                 1  14995.0
1  2016.0  Hatchback         42596.0  ...  Petrol                 3  10755.0
2  2015.0  Hatchback         42700.0  ...  Petrol                 2  10799.0

[3 rows x 9 columns]

In [ ]:
df.columns = ["yil","kasa","mil","motor","ps","vites","yakit","sahip","fiyat",]

In [ ]:
df.head(3)

      yil       kasa      mil motor          ps   vites   yakit  sahip    fiyat
0  2018.0  Hatchback  44000.0  1.6L  114.398422  Manual  Diesel      1  14995.0
1  2016.0  Hatchback  42596.0  1.0L   93.688363  Manual  Petrol      3  10755.0
2  2015.0  Hatchback  42700.0  1.4L  123.274162  Manual  Petrol      2  10799.0

In [ ]:
df["motor"] = df["motor"].str.replace("L","")
df["motor"] = pd.to_numeric(df["motor"])

In [ ]:
df = pd.get_dummies(df,columns=["kasa","vites","yakit"],drop_first=True)

In [ ]:
y = df[["fiyat"]]
x = df.drop("fiyat",axis = 1)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y,train_size=0.70,random_state=22)

In [ ]:
lm = LinearRegression()
model = lm.fit(x_train,y_train)
model.score(x_test,y_test)

0.9065438569490175

In [ ]:
#lm = LinearRegression()
#model = lm.fit(x,y)
#model.score(x,y)

0.9110559159967536

In [ ]:
df.head(3)

      yil      mil  motor  ...    fiyat  vites_Manual  yakit_Petrol
0  2018.0  44000.0    1.6  ...  14995.0          True         False
1  2016.0  42596.0    1.0  ...  10755.0          True          True
2  2015.0  42700.0    1.4  ...  10799.0          True          True

[3 rows x 8 columns]

In [ ]:
model.predict([[2016,30000,1.0,90,5,0,1]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[13704.96487686]])